### ISSUE TITLE
OVRO-LWA slow recorder png writing error

### ISSUE THREAD

**Issue by caseyjlaw** [lwa-project/ovro_data_recorder#12]
Noticed that the drslow recorder service was trying and failing to write a file.

```Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]: Traceback (most recent call last):
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:   File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/threading.py", line 916, in _bootstrap_inne
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:     self.run()
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:   File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/threading.py", line 864, in run
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:     self._target(*self._args, **self._kwargs)
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:   File "/home/ubuntu/ovro_data_recorder/dr_visibilities.py", line 524, in main
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:     mp.to_file(filename)
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:   File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/mnc_python-0.1.1_23_ga86862e_
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]:     with open(name_or_handle, 'wb') as fh:
Apr 05 17:13:47 lxdlwagpu09 dr-vslow-2[9299]: PermissionError: [Errno 13] Permission denied: '059675_001314_baselines.png'
```

**Comment by jaycedowell** [comment]
I've turned off the writing of the images to disk.  They will still be available through their respective monitoring points.
