### ISSUE TITLE
storage logger borks on etcd no route to host

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#33]
```
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011status = StatusCode.UNAVAILABLE
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011details = "No route to host"
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011debug_error_string = "{"created":"@1679339422.497068723","description":"Error received from peer ipv4:10.40.0.85:2379","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"No route to host","grpc_status":14}"
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: >
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: During handling of the above exception, another exception occurred:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: Traceback (most recent call last):
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/etcd3/watch.py", line 223, in _safe_callback
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    callback(response_or_err)
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py", line 361, in __call__
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    for evt in event.events:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: AttributeError: '_MultiThreadedRendezvous' object has no attribute 'events'
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: Watch callback failed
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: Traceback (most recent call last):
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/etcd3/watch.py", line 128, in _run
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    for rs in response_iter:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/grpc/_channel.py", line 426, in __next__
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    return self._next()
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _next
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    raise self
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011status = StatusCode.UNAVAILABLE
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011details = "No route to host"
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: #011debug_error_string = "{"created":"@1679339422.497068723","description":"Error received from peer ipv4:10.40.0.85:2379","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"No route to host","grpc_status":14}"
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: >
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: During handling of the above exception, another exception occurred:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: Traceback (most recent call last):
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/etcd3/watch.py", line 223, in _safe_callback
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    callback(response_or_err)
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py", line 361, in __call__
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]:    for evt in event.events:
Mar 20 19:10:22 lwacalim03 dr-vslow-5[27970]: AttributeError: '_MultiThreadedRendezvous' object has no attribute 'events'
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]: /home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py:586: RuntimeWarning: Error reading monitor point '/mon/drvs7801/bifrost/rx_missing': etcd connection failed
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]:  warnings.warn("Error reading monitor point '/mon/%s/%s': %s" % (id, name, str(e)), RuntimeWarning)
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]: /home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py:586: RuntimeWarning: Error reading monitor point '/mon/drvs7801/bifrost/max_process': etcd connection failed
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]:  warnings.warn("Error reading monitor point '/mon/%s/%s': %s" % (id, name, str(e)), RuntimeWarning)
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]: /home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py:586: RuntimeWarning: Error reading monitor point '/mon/drvs7801/storage/active_disk_size': etcd connection failed
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]:  warnings.warn("Error reading monitor point '/mon/%s/%s': %s" % (id, name, str(e)), RuntimeWarning)
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]: /home/pipeline/.conda/envs/datarecorder/lib/python3.6/site-packages/mnc/mcs.py:586: RuntimeWarning: Error reading monitor point '/mon/drvs7801/storage/active_disk_free': etcd connection failed
Mar 20 19:10:25 lwacalim03 dr-vslow-5[27970]:  warnings.warn("Error reading monitor point '/mon/%s/%s': %s" % (id, name, str(e)), RuntimeWarning)
```

**Comment by jaycedowell** [comment]
I'm not sure that is from `StorageLogger` since the loggers only read/write from etcd (like at the end of that block).  The trace points back to part of the `mnc.mcs.CommandCallbackBase` class which is used for incoming commands.  Did the info monitoring point show that `StorageLogger` had died as well?

**Comment by yupinghuang** [comment]
Yeah

**Comment by jaycedowell** [comment]
No idea on this one.  All of the etcd interfacing is handled through `mnc.mcs.Client`. 
 Everything in there related to reading and writing monitoring points looks to be robust to etcd problems.  It looks like the regular pipeline logfile has also been rotated out of existence so no clues there.
